/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesIndexRouteImport } from './routes/resources/_index'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog/rss[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog/_index'
import { Route as IndexHomeRouteImport } from './routes/_index/_home'
import { Route as ResourcesIndexIndexRouteImport } from './routes/resources/_index.index'
import { Route as IndexHomeIndexRouteImport } from './routes/_index/_home/index'
import { Route as BlogPostPostRouteImport } from './routes/blog/_post/_post'
import { Route as BlogIndexPostsRouteImport } from './routes/blog/_index/_posts'
import { Route as ApiImagesFeaturedRouteImport } from './routes/api/images/featured'
import { Route as BlogIndexTagsIndexRouteImport } from './routes/blog/_index/tags.index'
import { Route as BlogIndexPostsIndexRouteImport } from './routes/blog/_index/_posts.index'
import { Route as BlogPostPostSlugRouteImport } from './routes/blog/_post/_post.$slug'
import { Route as BlogIndexPostsNotesRouteImport } from './routes/blog/_index/_posts.notes'
import { Route as BlogIndexPostsExternalRouteImport } from './routes/blog/_index/_posts.external'
import { Route as BlogIndexTagsSlugIndexRouteImport } from './routes/blog/_index/tags.$slug.index'
import { Route as ApiImagesBlogPostCoverSlugRouteImport } from './routes/api/images/blog.post.cover.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/_index',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/_index',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexHomeRoute = IndexHomeRouteImport.update({
  id: '/_index/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexIndexRoute = ResourcesIndexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesIndexRoute,
} as any)
const IndexHomeIndexRoute = IndexHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndexHomeRoute,
} as any)
const BlogPostPostRoute = BlogPostPostRouteImport.update({
  id: '/blog/_post/_post',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexPostsRoute = BlogIndexPostsRouteImport.update({
  id: '/_posts',
  getParentRoute: () => BlogIndexRoute,
} as any)
const ApiImagesFeaturedRoute = ApiImagesFeaturedRouteImport.update({
  id: '/api/images/featured',
  path: '/api/images/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexTagsIndexRoute = BlogIndexTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => BlogIndexRoute,
} as any)
const BlogIndexPostsIndexRoute = BlogIndexPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogIndexPostsRoute,
} as any)
const BlogPostPostSlugRoute = BlogPostPostSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogPostPostRoute,
} as any)
const BlogIndexPostsNotesRoute = BlogIndexPostsNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => BlogIndexPostsRoute,
} as any)
const BlogIndexPostsExternalRoute = BlogIndexPostsExternalRouteImport.update({
  id: '/external',
  path: '/external',
  getParentRoute: () => BlogIndexPostsRoute,
} as any)
const BlogIndexTagsSlugIndexRoute = BlogIndexTagsSlugIndexRouteImport.update({
  id: '/tags/$slug/',
  path: '/tags/$slug/',
  getParentRoute: () => BlogIndexRoute,
} as any)
const ApiImagesBlogPostCoverSlugRoute =
  ApiImagesBlogPostCoverSlugRouteImport.update({
    id: '/api/images/blog/post/cover/$slug',
    path: '/api/images/blog/post/cover/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog': typeof BlogPostPostRouteWithChildren
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/resources': typeof ResourcesIndexRouteWithChildren
  '/api/images/featured': typeof ApiImagesFeaturedRoute
  '/': typeof IndexHomeIndexRoute
  '/resources/': typeof ResourcesIndexIndexRoute
  '/blog/external': typeof BlogIndexPostsExternalRoute
  '/blog/notes': typeof BlogIndexPostsNotesRoute
  '/blog/$slug': typeof BlogPostPostSlugRoute
  '/blog/': typeof BlogIndexPostsIndexRoute
  '/blog/tags': typeof BlogIndexTagsIndexRoute
  '/blog/tags/$slug': typeof BlogIndexTagsSlugIndexRoute
  '/api/images/blog/post/cover/$slug': typeof ApiImagesBlogPostCoverSlugRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog': typeof BlogIndexPostsIndexRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/api/images/featured': typeof ApiImagesFeaturedRoute
  '/': typeof IndexHomeIndexRoute
  '/resources': typeof ResourcesIndexIndexRoute
  '/blog/external': typeof BlogIndexPostsExternalRoute
  '/blog/notes': typeof BlogIndexPostsNotesRoute
  '/blog/$slug': typeof BlogPostPostSlugRoute
  '/blog/tags': typeof BlogIndexTagsIndexRoute
  '/blog/tags/$slug': typeof BlogIndexTagsSlugIndexRoute
  '/api/images/blog/post/cover/$slug': typeof ApiImagesBlogPostCoverSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_index/_home': typeof IndexHomeRouteWithChildren
  '/blog/_index': typeof BlogIndexRouteWithChildren
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/resources/_index': typeof ResourcesIndexRouteWithChildren
  '/api/images/featured': typeof ApiImagesFeaturedRoute
  '/blog/_index/_posts': typeof BlogIndexPostsRouteWithChildren
  '/blog/_post/_post': typeof BlogPostPostRouteWithChildren
  '/_index/_home/': typeof IndexHomeIndexRoute
  '/resources/_index/': typeof ResourcesIndexIndexRoute
  '/blog/_index/_posts/external': typeof BlogIndexPostsExternalRoute
  '/blog/_index/_posts/notes': typeof BlogIndexPostsNotesRoute
  '/blog/_post/_post/$slug': typeof BlogPostPostSlugRoute
  '/blog/_index/_posts/': typeof BlogIndexPostsIndexRoute
  '/blog/_index/tags/': typeof BlogIndexTagsIndexRoute
  '/blog/_index/tags/$slug/': typeof BlogIndexTagsSlugIndexRoute
  '/api/images/blog/post/cover/$slug': typeof ApiImagesBlogPostCoverSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sitemap.xml'
    | '/blog'
    | '/blog/rss.xml'
    | '/resources'
    | '/api/images/featured'
    | '/'
    | '/resources/'
    | '/blog/external'
    | '/blog/notes'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/tags'
    | '/blog/tags/$slug'
    | '/api/images/blog/post/cover/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/blog'
    | '/blog/rss.xml'
    | '/api/images/featured'
    | '/'
    | '/resources'
    | '/blog/external'
    | '/blog/notes'
    | '/blog/$slug'
    | '/blog/tags'
    | '/blog/tags/$slug'
    | '/api/images/blog/post/cover/$slug'
  id:
    | '__root__'
    | '/sitemap.xml'
    | '/_index/_home'
    | '/blog/_index'
    | '/blog/rss.xml'
    | '/resources/_index'
    | '/api/images/featured'
    | '/blog/_index/_posts'
    | '/blog/_post/_post'
    | '/_index/_home/'
    | '/resources/_index/'
    | '/blog/_index/_posts/external'
    | '/blog/_index/_posts/notes'
    | '/blog/_post/_post/$slug'
    | '/blog/_index/_posts/'
    | '/blog/_index/tags/'
    | '/blog/_index/tags/$slug/'
    | '/api/images/blog/post/cover/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IndexHomeRoute: typeof IndexHomeRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRouteWithChildren
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  ResourcesIndexRoute: typeof ResourcesIndexRouteWithChildren
  ApiImagesFeaturedRoute: typeof ApiImagesFeaturedRoute
  BlogPostPostRoute: typeof BlogPostPostRouteWithChildren
  ApiImagesBlogPostCoverSlugRoute: typeof ApiImagesBlogPostCoverSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/_index': {
      id: '/resources/_index'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/_index': {
      id: '/blog/_index'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_index/_home': {
      id: '/_index/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/_index/': {
      id: '/resources/_index/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexIndexRouteImport
      parentRoute: typeof ResourcesIndexRoute
    }
    '/_index/_home/': {
      id: '/_index/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexHomeIndexRouteImport
      parentRoute: typeof IndexHomeRoute
    }
    '/blog/_post/_post': {
      id: '/blog/_post/_post'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogPostPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/_index/_posts': {
      id: '/blog/_index/_posts'
      path: ''
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexPostsRouteImport
      parentRoute: typeof BlogIndexRoute
    }
    '/api/images/featured': {
      id: '/api/images/featured'
      path: '/api/images/featured'
      fullPath: '/api/images/featured'
      preLoaderRoute: typeof ApiImagesFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/_index/tags/': {
      id: '/blog/_index/tags/'
      path: '/tags'
      fullPath: '/blog/tags'
      preLoaderRoute: typeof BlogIndexTagsIndexRouteImport
      parentRoute: typeof BlogIndexRoute
    }
    '/blog/_index/_posts/': {
      id: '/blog/_index/_posts/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexPostsIndexRouteImport
      parentRoute: typeof BlogIndexPostsRoute
    }
    '/blog/_post/_post/$slug': {
      id: '/blog/_post/_post/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogPostPostSlugRouteImport
      parentRoute: typeof BlogPostPostRoute
    }
    '/blog/_index/_posts/notes': {
      id: '/blog/_index/_posts/notes'
      path: '/notes'
      fullPath: '/blog/notes'
      preLoaderRoute: typeof BlogIndexPostsNotesRouteImport
      parentRoute: typeof BlogIndexPostsRoute
    }
    '/blog/_index/_posts/external': {
      id: '/blog/_index/_posts/external'
      path: '/external'
      fullPath: '/blog/external'
      preLoaderRoute: typeof BlogIndexPostsExternalRouteImport
      parentRoute: typeof BlogIndexPostsRoute
    }
    '/blog/_index/tags/$slug/': {
      id: '/blog/_index/tags/$slug/'
      path: '/tags/$slug'
      fullPath: '/blog/tags/$slug'
      preLoaderRoute: typeof BlogIndexTagsSlugIndexRouteImport
      parentRoute: typeof BlogIndexRoute
    }
    '/api/images/blog/post/cover/$slug': {
      id: '/api/images/blog/post/cover/$slug'
      path: '/api/images/blog/post/cover/$slug'
      fullPath: '/api/images/blog/post/cover/$slug'
      preLoaderRoute: typeof ApiImagesBlogPostCoverSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IndexHomeRouteChildren {
  IndexHomeIndexRoute: typeof IndexHomeIndexRoute
}

const IndexHomeRouteChildren: IndexHomeRouteChildren = {
  IndexHomeIndexRoute: IndexHomeIndexRoute,
}

const IndexHomeRouteWithChildren = IndexHomeRoute._addFileChildren(
  IndexHomeRouteChildren,
)

interface BlogIndexPostsRouteChildren {
  BlogIndexPostsExternalRoute: typeof BlogIndexPostsExternalRoute
  BlogIndexPostsNotesRoute: typeof BlogIndexPostsNotesRoute
  BlogIndexPostsIndexRoute: typeof BlogIndexPostsIndexRoute
}

const BlogIndexPostsRouteChildren: BlogIndexPostsRouteChildren = {
  BlogIndexPostsExternalRoute: BlogIndexPostsExternalRoute,
  BlogIndexPostsNotesRoute: BlogIndexPostsNotesRoute,
  BlogIndexPostsIndexRoute: BlogIndexPostsIndexRoute,
}

const BlogIndexPostsRouteWithChildren = BlogIndexPostsRoute._addFileChildren(
  BlogIndexPostsRouteChildren,
)

interface BlogIndexRouteChildren {
  BlogIndexPostsRoute: typeof BlogIndexPostsRouteWithChildren
  BlogIndexTagsIndexRoute: typeof BlogIndexTagsIndexRoute
  BlogIndexTagsSlugIndexRoute: typeof BlogIndexTagsSlugIndexRoute
}

const BlogIndexRouteChildren: BlogIndexRouteChildren = {
  BlogIndexPostsRoute: BlogIndexPostsRouteWithChildren,
  BlogIndexTagsIndexRoute: BlogIndexTagsIndexRoute,
  BlogIndexTagsSlugIndexRoute: BlogIndexTagsSlugIndexRoute,
}

const BlogIndexRouteWithChildren = BlogIndexRoute._addFileChildren(
  BlogIndexRouteChildren,
)

interface ResourcesIndexRouteChildren {
  ResourcesIndexIndexRoute: typeof ResourcesIndexIndexRoute
}

const ResourcesIndexRouteChildren: ResourcesIndexRouteChildren = {
  ResourcesIndexIndexRoute: ResourcesIndexIndexRoute,
}

const ResourcesIndexRouteWithChildren = ResourcesIndexRoute._addFileChildren(
  ResourcesIndexRouteChildren,
)

interface BlogPostPostRouteChildren {
  BlogPostPostSlugRoute: typeof BlogPostPostSlugRoute
}

const BlogPostPostRouteChildren: BlogPostPostRouteChildren = {
  BlogPostPostSlugRoute: BlogPostPostSlugRoute,
}

const BlogPostPostRouteWithChildren = BlogPostPostRoute._addFileChildren(
  BlogPostPostRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IndexHomeRoute: IndexHomeRouteWithChildren,
  BlogIndexRoute: BlogIndexRouteWithChildren,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  ResourcesIndexRoute: ResourcesIndexRouteWithChildren,
  ApiImagesFeaturedRoute: ApiImagesFeaturedRoute,
  BlogPostPostRoute: BlogPostPostRouteWithChildren,
  ApiImagesBlogPostCoverSlugRoute: ApiImagesBlogPostCoverSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
